### ISSUE TITLE
Resize masks/placeholders if images of different sizes are compared

### ISSUE THREAD

**Issue by manykarim** [manykarim/robotframework-doctestlibrary#99]

**Comment by manykarim** [comment]
Pre-release created.

Test Results:

https://github.com/manykarim/robotframework-doctestlibrary/actions/runs/10819870656

**Comment by pZq** [comment]
> I created a prerelease 0.23.0dev0
> 
> You can install it via
> pip install --pre --upgrade robotframework-doctestlibrary
> 
> The images are now resized before applying the mask.
> This works only, with the argument resize_candidate=True
> 
> Pleae give it a try and give me a feedback in the GitHub issue.
> Thanks a lot.

I tested this out and seems like the mask is now converted correctly BUT the image recognition has some issues. So when reference image is larger than candidate the areas which are identical gets still some differences for some reason. So eg, the images below seems to me identical but still the comparison thinks there is differences. When ref and cand. is same size, the comparison is ok. Also tried the comparison with and without the blur=True argument.
![image](https://github.com/user-attachments/assets/03f808ab-1cb4-4899-9bdb-9788447d2c07)
![image](https://github.com/user-attachments/assets/23e9ad1e-46be-4ed8-a2ec-ebdabcc35d39)


with the main version, the comparison of the overal image was accepted without differences earlier BUT the mask was just scaled according to reference size.

[EDIT]
So did a little retest with official release and seems like the blur=True argument is ignored in the resizing case and thats why the overal image gets many difference findings.

**Comment by manykarim** [comment]
Thank you for trying it out 👍
Yeah, the problem with re-sizing is always that there will be some small artifacts in the resized image which will make a pixelwise comparison impossible.
I will look into the problem with the blur and create a new dev release later.
Hopefully this should solve it.

If even the blur will not create "equal" images, you could also play with the `threshold` argument.
Try setting it to very low values, e.g. `threshold=0.01`, `threshold=0.02`, .. and try to find the spot when the test passes.
Then you have reached the minimal difference which are still acceptable.

**Comment by manykarim** [comment]
ok, I created a new release `0.23.0.dev2`.
The blur behavior is now slightly different from the original version which might show in your results.
But I would ask you to give it a try anyway.

The main difference is:
In the previous release (before the change with resize and masks) the blur operation was done on the grayscale image (which is used for the visual comparison).
Now, the blur operation is done on the colored image (which is later converted to grayscale before the comparison).
For the time being, I cannot really adjust it, due to the structure of the library.
But I will try to find a better solution.

However, maybe it is good for you in your project.
Please give it a try and let me know the results

**Comment by peterlydman-insta** [comment]
The blur effect is now seen but it didnt help for reducing the differences on similar images.
I will check if treshold works in my case.

If you find something still to try to fix / change related to the blur attribute, let me know and i can test it out.

**Comment by manykarim** [comment]
If it helps, you can set the threshold already during library import, so you don't have to set it for each comparison separately. Maybe something you could do only for your local tests

**Comment by peterlydman-insta** [comment]
The treshold seems not to work that great at least in this pre-release
Its like the treshold scope is very very very accurate. So if i give a value of 0.0168 it still fails with same amount of differences than without the treshold attribute given at all. And when value is increased to 0.0169 the test passes and there is no differences in images anymore, even normal sized text changes is not noticed. There is a time and date text which has one character (number) difference and its not failing on it. So there is still some issues in this.

To recap
Test 1: (with mask)
Testing with resize_candidate=True -> mask is scaled correctly

Test 2: (observe -> no mask)
resize_candidate=True    blur=True -> Blurs the image, test fails only on major changes like if one character differs from reference (this working nicely to this point)

Test 3: (observe with mask )
resize_candidate=True    blur=True  with MASK ->The whole image gets very many differences.. This is not working as expected compared to Test 2. I would assume that is Test 2 is ok, then test 3 should pass the test due to the MASK.

So there is still something wrong in case of Resize, blur and mask combination

**Comment by manykarim** [comment]
Great summary, thanks a lot @peterlydman-insta .
Is there any chance you could provide your test data or is that data restricted?
I would really like to use it locally for my tests, to have a proper solution.
I will approach you via a direct message

**Comment by pZq** [comment]
Yes and sorry for the 2 acco confusement. This is my account that i should use but that other one was left in the cache or somehting and in mistake i used that account... I will try to make testdata for you that could be used to repoduce this issue.

**Comment by peterlydman-insta** [comment]
Note that i have commented out the treshold, take_scrshot and show_diff from arguments.
an other thing i noted but not 100% sure is that the blur argument in official release didnt blur the resulting images in report. 
I cannot confirm this now. I just have a feeling it didnt -> but i might be wrong.

[logs.zip](https://github.com/user-attachments/files/16989671/logs.zip)
[Images_and_mask.zip](https://github.com/user-attachments/files/16989729/Images_and_mask.zip)

```
*** Settings ***
Documentation     Simple test
Library    DocTest.VisualTest    screenshot_format=jpg    #threshold=0.0169    #take_screenshots=True   #show_diff=True

*** Variables ***
${REFERENCE_DIR}    ${CURDIR}/CV/Reference
${CANDIDATE_DIR}    ${CURDIR}/CV/Candidate
${MASK_DIR}    ${CURDIR}/CV/Masks

*** Test Cases ***
Check that Ref.jpg and Can.jpg are similar even resolution is different
    CV_CompareImages    img.jpg
    CV_CompareImages    img.jpg    img_mask.json

*** Keywords ***
CV_CompareImages
    [Arguments]    ${filename}    ${mask}=${EMPTY}
    [Documentation]    Compare two images and fail if they are not similar enough. Give filename with extension eg. "image.jpg"
    Sleep    1
    #Capture Page Screenshot    ${CANDIDATE_DIR}\\${filename}
    IF    "${mask}" == "${EMPTY}"
        Run Keyword And Continue On Failure    Compare Images    ${REFERENCE_DIR}/${filename}    ${CANDIDATE_DIR}/${filename}    resize_candidate=True    blur=True
    ELSE
        Run Keyword And Continue On Failure    Compare Images    ${REFERENCE_DIR}/${filename}    ${CANDIDATE_DIR}/${filename}    resize_candidate=True    blur=True    placeholder_file=${MASK_DIR}/${mask}
    END 
```

**Comment by pZq** [comment]
Note that i have commented out the treshold, take_scrshot and show_diff from arguments.
an other thing i noted but not 100% sure is that the blur argument in official release didnt blur the resulting images in report. 
I cannot confirm this now. I just have a feeling it didnt -> but i might be wrong.

The logs will show you the issue.
[logs.zip](https://github.com/user-attachments/files/16989671/logs.zip)

If you want to run your own test, here is the ref + candidate images and mask.
[Images_and_mask.zip](https://github.com/user-attachments/files/16989729/Images_and_mask.zip)

```
*** Settings ***
Documentation     Simple test
Library    DocTest.VisualTest    screenshot_format=jpg    #threshold=0.0169    #take_screenshots=True   #show_diff=True

*** Variables ***
${REFERENCE_DIR}    ${CURDIR}/CV/Reference
${CANDIDATE_DIR}    ${CURDIR}/CV/Candidate
${MASK_DIR}    ${CURDIR}/CV/Masks

*** Test Cases ***
Check that Ref.jpg and Can.jpg are similar even resolution is different
    CV_CompareImages    img.jpg
    CV_CompareImages    img.jpg    img_mask.json

*** Keywords ***
CV_CompareImages
    [Arguments]    ${filename}    ${mask}=${EMPTY}
    [Documentation]    Compare two images and fail if they are not similar enough. Give filename with extension eg. "image.jpg"
    Sleep    1
    #Capture Page Screenshot    ${CANDIDATE_DIR}\\${filename}
    IF    "${mask}" == "${EMPTY}"
        Run Keyword And Continue On Failure    Compare Images    ${REFERENCE_DIR}/${filename}    ${CANDIDATE_DIR}/${filename}    resize_candidate=True    blur=True
    ELSE
        Run Keyword And Continue On Failure    Compare Images    ${REFERENCE_DIR}/${filename}    ${CANDIDATE_DIR}/${filename}    resize_candidate=True    blur=True    placeholder_file=${MASK_DIR}/${mask}
    END 
```

**Comment by manykarim** [comment]
I have an idea for a significant improvement, but I’d like to get your input on it.

Currently, when two images differ (pixel-wise), the library uses the Structural Similarity (SSIM) algorithm to calculate a similarity score. By adjusting the threshold parameter, we can allow for some flexibility when comparing images with minor artifacts or noise.

The issue is that SSIM is calculated over the entire image. This can result in small but important differences (e.g., a single letter) being overlooked, as the overall score may still be high enough for the test to pass.

My suggestion is to modify the approach by dividing the image into a grid and calculating SSIM for each block that contains differences. This way, small differences, such as a different letter, number, or symbol, would have a greater impact and trigger a test failure, while noise-related differences could still be filtered out.

Do you have an opinion on it?

**Comment by pZq** [comment]
Any update on this -> Is it a harder rework or is there some estimate when this new implementation might be testable ?

**Comment by manykarim** [comment]
I think this new implementation might take a bit longer. I can say more once I have started coding it. But I think more towards the end of the month. That's more like a new major release and will bring other improvements to the library. 
I'm struggling with finding a proper solution for the change that I already released in the pre-release that you tested. 
Hoping to find some time for it tomorrow. If I have an idea, I'd release it on short notice, end of this week.
But if I can't figure out, I think I'd be better focus on the major rework instead of doing that temporary workaround.

**Comment by manykarim** [comment]
Just wanted to let you know that the major refactoring is now in progress. Let's see how quick it goes..

**Comment by manykarim** [comment]
Refactoring still ongoing, but slowly we're getting there
https://github.com/manykarim/robotframework-doctestlibrary/actions/runs/11160768563

**Comment by pZq** [comment]
Good to hear. Just let me know when there is something to test and i will do it 👍

**Comment by pZq** [comment]
Hii @manykarim , has there been any time to progress this refactoring development ?

**Comment by pZq** [comment]
@manykarim Any news on this refactoring stuff ? Is it on hold or do you have any update on this one ?

**Comment by manykarim** [comment]
Hey @pZq ,
somehow was busy with other things, sorry for the long silence.
Anyway, I did some polishing today and I think we're ready for a release candidate.

I will release it as a prerelease on PyPi now, but will need a few days to complete the release documentation.

You can install it via
`pip install --pre robotframework-doctestlibrary`

There are a lot of changes, but for your example there were some improvements with the `blur` and also with a new comparison approach `block_based_ssim=True` , to split up the image into smaller blocks and compare the blocks separately. 

```
*** Settings ***
Library    DocTest.VisualTest    show_diff=true    take_screenshots=true    screenshot_format=png

*** Test Cases ***
Compare images with different sizes , blur and threshold
    Compare Images    testdata/debug/reference.jpg   testdata/debug/candidate.jpg    resize_candidate=True    blur=True    threshold=0.01

Compare images with different sizes , blur and threshold and block_based_ssim
    Run Keyword And Expect Error      The compared images are different.      Compare Images    testdata/debug/reference.jpg   testdata/debug/candidate.jpg    resize_candidate=True    blur=True    threshold=0.01    block_based_ssim=True    block_size=32
```

**Comment by pZq** [comment]
Cool, Seems like it works better now. I'll report if i find some issues later, latest on this week end

**Comment by pZq** [comment]
Ok. After quite extensive testing i got it working. BUT move_tolerance parameter set to eg. move_tolerance=1 or 5 or 10 makes a test pass that should fail.

I will try to describe it here.
![Image](https://github.com/user-attachments/assets/3233c51e-cd6f-4b2f-aa01-54efe51ee513)

I have a date field which is expected to be in format DD.MM.YYYY but in the test the actual image had DD/MM/YYYY. It will fail the comparison when not using move_tolerance parameter but some parts of the image shows highlighted failures because that the content has slightly shifted.

So in the small screenshot above. with move_tolerance=10  i expected that it allows the "Active" text to be shiftd by 10 pixels but still fail the date string comparison BUT when i set the move_tolernace=10 -> the test passes. The small screenshot is taken from comparison when move_tolerance is not used. 

**This passes test but should fail ?**
Compare Images    ${REFERENCE_DIR}/${filename}    ${CANDIDATE_DIR}/${filename}    placeholder_file=${MASK_DIR}/${mask}    block_based_ssim=True    block_size=32    threshold=0.5    resize_candidate=True    blur=True    move_tolerance=10

**This fails test as expected**
Compare Images    ${REFERENCE_DIR}/${filename}    ${CANDIDATE_DIR}/${filename}    placeholder_file=${MASK_DIR}/${mask}    block_based_ssim=True    block_size=32    threshold=0.5    resize_candidate=True    blur=True

**My question is -> how does the move_tolerance parameter affect the whole assertion ?**

**Comment by manykarim** [comment]
Thanks for the feedback @pZq . Really appreciate it.

Could you do me a favor and import the Library with argument `movement_detection=sift` and give it another try.

```
*** Settings ***
Library    DocTest.VisualTest    movement_detection=sift
````

It is a "new" type of movement detection in introduced in the new release.
But I did not want to enable it by default.

https://medium.com/analytics-vidhya/opencv-feature-matching-sift-algorithm-scale-invariant-feature-transform-16672eafb253
https://docs.opencv.org/4.x/da/df5/tutorial_py_sift_intro.html

**Comment by pZq** [comment]
Area {'x': 1927, 'y': 1087, 'width': 46, 'height': 18} is moved 0 pixels.
Area {'x': 1775, 'y': 1087, 'width': 85, 'height': 18} is moved 0 pixels.
Area {'x': 378, 'y': 366, 'width': 1607, 'height': 198} is moved 1 pixels.
Area {'x': 1779, 'y': 209, 'width': 191, 'height': 19} is moved 0 pixels.
Could not compare areas: cannot convert float NaN to integer

There is one error / warning in output after using move_tolerance

But otherwise it works now better -> move_tolernace doesn't pass test that should fail. Also the highlighting makes more sense now. Doesnt show many moved sections. Well eg in tables if date field expands a bit and other columns moves to left or right, there will be highlightings on those but i think i can live with those since the combined difference map image shows where the actual issue is.

Also one note was that when no  blur parameter is given -> its not as good difference results as when blur=True for some reason. Result is more unpredictable -> or tests that should fail passes even with threshold of 0.0001

**Comment by manykarim** [comment]
ok, let me summarize:
It's a mess 🙈

But one question:

> Also one note was that when no blur parameter is given -> its not as good difference results as when blur=True for some reason. Result is more unpredictable -> or tests that should fail passes even with threshold of 0.0001

Are you referring to comparisons (without blur) in general?
Or only when doing comparisons without blur and `move_tolerance` ?

**Comment by pZq** [comment]
I was using now:
`Library    DocTest.VisualTest    screenshot_format=png    take_screenshots=True    show_diff=True    movement_detection=sift
`
`Compare Images    ${REFERENCE_DIR}/${filename}    ${CANDIDATE_DIR}/${filename}    placeholder_file=${MASK_DIR}/${mask}    block_based_ssim=True    block_size=32    threshold=0.5    resize_candidate=True    move_tolerance=500    blur=True`
vs
`Compare Images    ${REFERENCE_DIR}/${filename}    ${CANDIDATE_DIR}/${filename}    placeholder_file=${MASK_DIR}/${mask}    block_based_ssim=True    block_size=32    threshold=0.5    resize_candidate=True    move_tolerance=500`

And without the blur parameter the test didnt react anymore to eg date difference DD.MM.YYYY vs DD/MM/YYYY
With blur parameter that date format difference was caught "red handed".

**Comment by pZq** [comment]
The main issue seems to lie in the fact that in our SW the whole page content is slightly shifted depending on date format which is unnoticable by eye.

This in case makes the image comparison to highlight different sections of image that was only moved but not changed.

Check image attached. I tweeked some parts of image with paint (shifted text a bit and then change a text usif F12 dev tools)

the result is this
![Image](https://github.com/user-attachments/assets/1dbd6d96-784a-442c-be47-be7bc852ace8)

As you see the highlighting now reacts to basically to sections that was not changed but rather moved and the text [TWEEK] was not noticed at all.

When i only change text without shifting content it finds and highlights the correct spot.
![Image](https://github.com/user-attachments/assets/9d0886f6-1154-4b14-9ea8-69e38c7e63a1)

So all in all. Seem that it works BUT its very hard to find the spot that was the rootcause of failure if page content is shifted WHILE some part of page is "inconsistent" compared to reference.

**Comment by pZq** [comment]
The main issue seems to lie in the fact that in our SW the whole page content is slightly shifted depending on date format which is unnoticable by eye.

This in case makes the image comparison to highlight different sections of image that was only moved but not changed.

Check image attached. I tweeked some parts of image with paint (shifted text a bit and then change a text usif F12 dev tools)

the result is this
![Image](https://github.com/user-attachments/assets/ecf171f9-9914-408f-84a4-05da55ea5e7b)

As you see the highlighting now reacts to basically to sections that was not changed but rather moved and the text [TWEEK] was not noticed at all.

When i only change text without shifting content it finds and highlights the correct spot.
![Image](https://github.com/user-attachments/assets/de704eb7-f350-4680-9ae3-245fb252e16c)

So all in all. Seem that it works BUT its very hard to find the spot that was the rootcause of failure if page content is shifted WHILE some part of page is "inconsistent" compared to reference.

**Comment by manykarim** [comment]
> The main issue seems to lie in the fact that in our SW the whole page content is slightly shifted depending on date format which is unnoticable by eye.

Ah, that's interesting.
So that would mean: If the page section "after" that dated is moved, it could match exactly to your original page?

In the newest release, I also introduced a Keyword [Image Should Contain Template](https://manykarim.github.io/robotframework-doctestlibrary/VisualTest_0.24.0rc1.html#Image%20Should%20Contain%20Template)

The purpose is, to find a smaller partial image inside a bigger image.
So maybe if we "crop" your new image from the application - so the "date part" is not in there - and only compare the remaining image, it could maybe proof that the partial image exists.

**Comment by pZq** [comment]
I will do a test with that next week and i will report how it works in my case.

**Comment by pZq** [comment]
I ran the tests over weekend and results are good. It seems that there might be either some issue with resize_candidate function OR then there is some Aspect_ratio mismatch between laptop recorder screenshots vs pipeline recorded screenshots.

I cannot still say what the real issue since when i run the JS height width requests the pipeline say aspect_ratio = 1.33 (resolution 1024x768) and when i run it locally the aspect ratio is 1.77 (resolution 1920x1080).
The only thing i can say is -> when my local main screen is a 1920x1080 resolution display, the screen capture resolutions are equal both locally and in pipeline (resolution 1904x933) And when the images are equal -> also the image recognition is very precise and only the failing digits of the date is highlighted.

Dunno if my observations helps at all but yeah. My feeling is currently -> setup systems so that that reference vs candidate resolutions are same to get best results.
